# This file is autogenerated. Instead of editing this file, please use the
# migrations feature of ActiveRecord to incrementally modify your database, and
# then regenerate this schema definition.

ActiveRecord::Schema.define(:version => 3) do

  create_table "images", :force => true do |t|
    t.column "parent_id",    :integer
    t.column "content_type", :string
    t.column "filename",     :string
    t.column "thumbnail",    :string
    t.column "size",         :integer
    t.column "width",        :integer
    t.column "height",       :integer
    t.column "caption",      :string
    t.column "type",         :string
    t.column "project_id",   :integer
    t.column "position",     :integer
  end

  create_table "projects", :force => true do |t|
    t.column "name",              :string
    t.column "description",       :text
    t.column "completed",         :date
    t.column "construction_cost", :decimal, :precision => 20, :scale => 2
  end

end
